lesson-1
PavelIlyin/JS-advanced-level pull request #1
Opened 2021-02-19 12:01 UTC by PavelIlyin

completed homework

2021-02-20 11:46 UTC, Om1X requested changes

2021-02-20 11:46 UTC, Om1X commented on js/main.js
> +});
Соблюдаем общую структуру кода. У нас было 2 функции, сейчас одна, не надо "ломать" целостность кода. Верните функцию, но с учетом Вашей правки

2021-02-22 15:43 UTC, PavelIlyin reviewed
Corrected taking into account the comments

2021-02-24 14:05 UTC, Om1X approved these changes

2021-02-25 11:57 UTC, merged